### ISSUE TITLE
Changing the fuel value

### ISSUE THREAD

**Issue by malintha** [mitrefireline/simfire#1]
### Let me first say thank you for releasing this cool simulator!

I have a couple of questions on using the simulator.

1) How can we change the fuel value of a cell programmatically, say to evaluate the effect of removing the fuel to contain the fire?

2) Where can we find the topological and fuel data for the `operational` configurations? I tried using a topological map downloaded from the usgs website, but not sure about the format of the data, since it complained `FileNotFoundError: [Errno 2] No such file or directory: 'data/fuel/30m/2019'`.

Thanks!

**Comment by doyled-it** [comment]
Thank you for saying so and thank you for using our fire simulator that is still very much a work in progress!

I can answer 1 for you, but will have to ask @mdotter-mitre to answer 2 if I don't answer it well enough here:

1. The `Simulation` object that you would create to use this has an attribute `terrain` which should have all the fuel values in its `fuels` attribute (e.g., `sim.terrain.fuels`). In this NumPy array, at every (y, x) location, is a [`Fuel`](https://github.com/mitrefireline/simfire/blob/a58320f681944aef364bbbb7224a326707edc409/simfire/world/parameters.py#L31) object that contains the fuel information. You can change this individually, which I would **not** the recommended, but could be done. I **would** recommend staying at the `Simulation` level and applying a mitigation to a cell with the [`update_mitigation`](https://github.com/mitrefireline/simfire/blob/a58320f681944aef364bbbb7224a326707edc409/simfire/sim/simulation.py#L410) function. Right now there are only [three types](https://github.com/mitrefireline/simfire/blob/a58320f681944aef364bbbb7224a326707edc409/simfire/game/managers/mitigation.py#L83) of mitigation and they can [attenuate the spread rate to varying degrees](https://github.com/mitrefireline/simfire/blob/a58320f681944aef364bbbb7224a326707edc409/simfire/enums.py#L72) if you change [this value in the config](https://mitrefireline.github.io/simfire/config.html#ros-attenuation) to `true`.
2. At the moment, we don't have a mechanism for downloading the `operational` fuel and topography data from their respective sources and putting it into the correct format to be loaded by the simulator. As far as I know @mdotter-mitre is working on a different way of loading this data that is much quicker and after that development may come a way to download this data.

**Comment by mdotter-mitre** [comment]
Hi @malintha!

Regarding the second part of your question, fuel and topography data is currently being downloaded from LandFire (https://landfire.gov/version_download.php) using the 13 Anderson Fire Behavior Fuel Models for the respective year you are interested in using. 
The current version of SimFire uses WGS84 1 degree x 1 degree "tiles" to load this data, but we are hoping our next release will have the following implemented:
-  use the CONUS version of this data, rather than individual tiles
- scripts that scrape and download the data
- New Fuel and Topography dataloaders

For immediate use of SimFire with operational data, I recommend downloading a tile that is an area-of-interest to you, and adding it to the folder path `data/fuel/30m/<year>`. These individual tiles can be downloaded using LandFire's Download tool: https://www.landfire.gov/viewer/

**Comment by doyled-it** [comment]
@malintha As of [version 1.5.0](https://pypi.org/project/simfire/), the data required for operational fuel data for a specified lat, long will be downloaded to your [`sf_home` directory](https://mitrefireline.github.io/simfire/config.html#sf-home). And that download will be handled in the background, so no need to download and format fuel data to fit the simulator ahead of time.

**Comment by doyled-it** [comment]
Closing issue for now.
